services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Mr\NewsApiBundle\Service\NewsClient:
        arguments:
          $apiKey: '%news_api.api_key%'
