language: php
sudo: true

cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client


before_install:
  - sleep 10
  - composer self-update

install:
  - composer install
  - ./bin/phpunit install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test

script:
  - ./bin/console lint:yaml config
  - ./bin/console lint:twig templates
  - ./bin/console lint:xliff translations
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
  - ./bin/console d:f:l --append  --env=test
  - ./bin/phpunit  ./tests/Unit/

services:
  - mysql
  - elasticsearch
