home_most_read:
  path: /most_read
  controller: App\Controller\HomeController::getMostRead
category_more_read:
  path: /{categorySlug}/more_read
  controller: App\Controller\CategoryController::getMoreRead
new_more_read:
  path: /new/most_read
  controller: App\Controller\NewController::getMoreRead
