login:
  path: /login
  controller: App\Controller\SecurityController::login

register:
  path: /register
  controller: App\Controller\SecurityController::register

home:
  path: /
  controller: App\Controller\HomeController::index

article_page:
  path: /article/{slug}
  controller: App\Controller\Article\ArticleController::index

category_page:
  path: /category/{slug}
  controller: App\Controller\CategoryController::index

new_page:
  path: /new
  controller: App\Controller\Article\NewController::index

popular_page:
  path: /popular
  controller: App\Controller\Article\PopularController::index

subscriber_form:
  path: /subscriber/form
  methods: [POST]
  controller:  App\Controller\SubscriberController::subscribe

search:
  path: /search
  controller: App\Controller\SearchController::index

unsubscribe:
  path: /unsubscribe/{token}
  controller:  App\Controller\SubscriberController::unsubscribe

tag_page:
  path: /tag/{slug}
  controller:  App\Controller\TagsController::index

user_articles_create:
  path: /user/articles/create
  controller:  App\Controller\User\ArticleController::create

user_articles_index:
  path: /user/articles
  controller:  App\Controller\User\ArticleController::index
