#index:
#    path: /
#    controller: App\Controller\DefaultController::index
admin:
  prefix: /admin
  resource: './routes/admin_routes.yaml'

api:
  prefix: /api
  resource: './routes/api_routes.yaml'

pages:
  prefix: /{_locale}
  resource: './routes/with_locale_prefix.yaml'
  requirements:
    _locale:  en|ua

logout:
  path: /logout

subscriber_form:
  path: /subscriber/form
  methods: [POST]
  controller:  App\Controller\LayoutController::subscribeUser
