#index:
#    path: /
#    controller: App\Controller\DefaultController::index
admin:
  prefix: /admin
  resource: './routes/admin_routes.yaml'
login:
  path: /login
  controller: App\Controller\SecurityController::login
register:
  path: /register
  controller: App\Controller\SecurityController::register
logout:
  path: /logout
home:
  path: /
  controller: App\Controller\HomeController::index
article_page:
  path: /article/{slug}
  controller: App\Controller\ArticleController::index
