#index:
#    path: /
#    controller: App\Controller\DefaultController::index
admin:
  prefix: /admin
  resource: './routes/admin_routes.yaml'
api:
  prefix: /api
  resource: './routes/api_routes.yaml'
login:
  path: /login
  controller: App\Controller\SecurityController::login
register:
  path: /register
  controller: App\Controller\SecurityController::register
logout:
  path: /logout
home:
  path: /
  controller: App\Controller\HomeController::index
article_page:
  path: /article/{articleSlug}
  controller: App\Controller\ArticleController::index
category_page:
  path: /category/{categorySlug}
  controller: App\Controller\CategoryController::index
new_page:
  path: /new
  controller: App\Controller\NewController::index
popular_page:
  path: /popular
  controller: App\Controller\PopularController::index
