with_locale_prefix:
  prefix:
   en: /
   ua: /ua
  resource: ./routes/with_locale_prefix.yaml

custom_admin:
  prefix: /custom-admin
  resource: ./routes/admin_routes.yaml

logout:
  path: /logout

api_v1:
  prefix: /api
  resource: ./routes/api_v1.yaml

api:
  prefix: /ajax
  resource: ./routes/api_routes.yaml
